apiVersion: v1
kind: Service 
metadata:
  name: address-service  
spec:
  ports:
  - port: 30089
    nodePort: 30089
    targetPort: 8083-port
    protocol: TCP
  selector:
    app: address 
  type: NodePort
