apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-deployment
  labels:
    app: address
spec:
  replicas: 1
  selector:
    matchLabels:
      app: address
  template:
    metadata:
      labels:
        app: address
    spec:
      containers:
      - name: address
        image: eu.gcr.io/warm-mediator-193214/address-app
        ports:
        - name: 8080-port
          containerPort: 8080
        envFrom:
        - configMapRef:
             name: config-env-file