apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: address-deployment
  labels:
    app: address
spec:
  replicas: 1
  selector:
    matchLabels:
      app: address
  template:
    metadata:
      labels:
        app: address
    spec:
      containers:
      - name: address
        image: valeriocordoni/addresses:1.0.0
        ports:
        - name: 8083-port
          containerPort: 8083
        envFrom:
        - configMapRef:
             name: config-env-file
